### ISSUE TITLE
Support for MongoDB 2.x

### ISSUE THREAD

**Issue by ayosec** [mongodb-labs/mongo-rust-driver-prototype#122]
I'm not able to use this library against a MongoDB 2.4 database.

I [changed the `travis.yml`](https://github.com/ayosec/mongo-rust-driver-prototype/commit/ea102f6df9409059e6d693869cd9711e1ed23dec) to launch tests with [multiple versions](https://travis-ci.org/ayosec/mongo-rust-driver-prototype/builds/77932949). Only 3.0.3 is working.

* [Results for 2.6.11](https://travis-ci.org/ayosec/mongo-rust-driver-prototype/jobs/77932951): `84 passed; 10 failed`
* [Results for 2.4.14](https://travis-ci.org/ayosec/mongo-rust-driver-prototype/jobs/77932954): `44 passed; 50 failed`

**Comment by saghm** [comment]
It looks like most of the errors are caused by API-breaking changes between 2.x and 3.x. I don't think there are any plans to add support for 2.x, although you're welcome to submit a pull request.

**Comment by vkarpov15** [comment]
@saghm is right. One of the reasons why this is a prototype rather than a full-fledged driver is that it's only expected to work with MongoDB 3.0.x right now. If there's a lot of demand we're happy to work on it, but we don't quite have the spare cycles to add 2.4 / 2.6 support right now.

**Comment by thijsc** [comment]
Try https://github.com/thijsc/mongo-rust-driver, this driver does support MongoDB 2.x.

**Comment by ayosec** [comment]
@thijsc Your crate works pretty well. Thanks you!

I'm closing the issue. People who need to connect to Mongo 2 can use [mongo_driver](https://crates.io/crates/mongo_driver/).
