### ISSUE TITLE
Question on how to use update_one function 

### ISSUE THREAD

**Issue by dzobbe** [mongodb-labs/mongo-rust-driver-prototype#124]
Hi,

I am having problem with update_one function. I want store time series data in MongoDB and, as suggested in many tutorials, I want to store one minute per document and each second I would like to store in a vector field the measurement. My question is: how can I update the vector inside the document? How can I add each second a new measurement value?

Thanks in advance guys.

**Comment by vkarpov15** [comment]
Does `$push` not work?

```
let update = doc! { "$push" => { "minutes.5" => 25 } };
db.collection('times').update_one(query, update, None).ok().expect("update failed");
```

**Comment by saghm** [comment]
This should probably be all right to close now, given that there hasn't been any response for a few months.

**Comment by vkarpov15** [comment]
Yep good call
