### ISSUE TITLE
Does this driver currently support $and?

### ISSUE THREAD

**Issue by veer66** [mongodb-labs/mongo-rust-driver-prototype#129]
I try to use doc! {"$and": [cond1, cond2]} but it doesn't work. I'm not sure whether it is not supported or I didn't do it properly.

**Comment by saghm** [comment]
I don't think there's a `$doc` operator; is that just a typo in your comment?

**Comment by vkarpov15** [comment]
@saghm is right. We have tests in place for `$and`, so in theory that should work. `$doc` is not expected to work though.

**Comment by veer66** [comment]
Excute me. It should be $and, not $doc.

**Comment by vkarpov15** [comment]
Define "doesn't work" - that's a very nebulous bug report. Can you provide some sample code that reproduces this issue?

**Comment by veer66** [comment]
"We have tests in place for $and, so in theory that should work." 

Thank you for the confirmation.
