### ISSUE TITLE
How to convert mongo bson objectId to a string

### ISSUE THREAD

**Issue by paul** [mongodb-labs/mongo-rust-driver-prototype#134]
Apologies if this is the wrong place to ask, as its not really an issue with a code itself, but rather a failure of me understanding the documentation. I'm working on a tool to sync a collection of mongo documents to a postgres database. Here is the code in its entirety: http://is.gd/QYzkBD

This works, except the existing document ids get stored in the postgres text column as the string `ObjectId("566740710ed3bc0a8f000001")`, and I need them as just the hex part. I've read the docs and the mongo driver source, but I can't figure out how to convert it to that. It looks like `ObjectId` had a `to_hex` function which is what I think I need, but the result of `.get("_id")` is of `Bson` type, so I get `error: no method named `to_hex` found for type `&bson::bson::Bson` in the current scope`

I'm still unfamiliar enough with rust to know how to convert from `Bson` to the underlying `ObjectId`, or if there is a better approach that I'm missing. Thanks!

**Comment by saghm** [comment]
`to_hex()` is a method of the trait `ToHex` in the `rustc_serialize` crate. You'll need to import that trait if you want to be able to use the methods of it.

https://doc.rust-lang.org/rustc-serialize/rustc_serialize/hex/trait.ToHex.html

**Comment by vkarpov15** [comment]
Thanks @saghm
