### ISSUE TITLE
Client::connect does not error as I would expect

### ISSUE THREAD

**Issue by thetyrelcorporation** [mongodb-labs/mongo-rust-driver-prototype#137]
Hello, first of all thank you for your work on a pure rust mongodb driver.

While I was experimenting I noticed that the client connect Err match does not execute when a server is down. The program didn't panic until the client was used later and then responded with: thread '<main>' panicked at 'Failed to insert document becuase: No servers available for the provided ReadPreference.

This should have picked up that there was no mongod server running
	let client = match Client::connect("localhost", 27017) {
		Ok(c) => c,
		Err(e) => {
			panic!("Failed to initialize standalone client: {}", e);
		},
	};

However it continued to later panic here
	match coll.insert_one(doc.clone(), None) {
		Ok(_) => println!("Inserted document:"),
		Err(err) => panic!("Failed to insert document becuase: {}", err),
	}

Just an observation. Again it's working great so far.

**Comment by saghm** [comment]
This is a good point; I hadn't realized it until debugging @135, and after that I figured that it would come up at some point. From an API standpoint, it is kind of strange to have that error not occur until the first query/insertion is sent to the database.

Probably the simplest way to fix it would be to do some trivial query in the constructor for `Client` to find a possible bad connection and report it (and otherwise drop any result that comes back). @kyeah @vkarpov15, do you think this is a reasonable solution? I can submit a pull request with the change if there are no objections.

**Comment by kyeah** [comment]
This is an interesting behavior with regards to MongoDB's drivers, but one that is outlined in the current specifications, found [here](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring-summary.rst#client-construction).

> A multi-threaded or asynchronous client's constructor MUST NOT do any I/O. The constructor MAY start the monitors as background tasks, or they MAY be started by some "initialize" method (by any name), or on the first use of the client for an operation. This means that the constructor does not throw an exception if the deployment is unavailable: Instead, all subsequent operations on the client fail as long as the error persists.

> The justification is that if clients can be constructed when the deployment is in some states but not in other states, it leads to an unfortunate scenario: When the deployment is passing through a strange state, long-running applications may keep working, but any applications restarted during this period fail.

> Additionally, since asynchronous clients cannot do I/O in a constructor, it is consistent to prohibit I/O in other clients' constructors as well.

> Single-threaded clients also MUST NOT do I/O in the constructor. They scan the servers on demand, when the first operation is attempted. Thus they behave consistently with multi-threaded and asynchronous clients.

**Comment by saghm** [comment]
Ah, okay, I was not aware this was intentional. Thanks @kyeah!

**Comment by thetyrelcorporation** [comment]
Learn something new everyday. It is what it is. Thanks for looking into it.
