### ISSUE TITLE
~40ms find_one function on small collection

### ISSUE THREAD

**Issue by freiguy1** [mongodb-labs/mongo-rust-driver-prototype#141]
I'm working on a web api and having been trying to diagnose slow performance issues. Some of my endpoints take 400-500ms without doing much of anything.  I put some timers in my code, and found that mongodb calls were the slow ones.  I then decided to create a very slimmed down version of what I was doing to showcase the slowness in an issue.  I'm new to mongodb so I may be doing something which isn't recommended.  Below, I'll copy my Cargo.toml, main.rs, and output. I'm  using rust nightly from Mar. 8th 2016 since there are still build issues with running everything at latest including latest nightly.

Cargo.toml dependencies:
```
serde = "0.6"
serde_macros = "0.6"

mongodb = "0.1"
bson = "0.1"
```

main.rs:
``` rust
#![feature(custom_derive, plugin)]
#![plugin(serde_macros)]

#[macro_use(bson, doc)]
extern crate bson;
extern crate mongodb;
extern crate serde;
extern crate chrono;

use bson::{Document, Bson};
use mongodb::{Client, ThreadedClient};
use mongodb::db::{Database, ThreadedDatabase};
use mongodb::coll::Collection;
use serde::{Serialize, Deserialize};
use chrono::*;

#[derive(Serialize, Deserialize, Debug)]
struct MyDocument {
    #[serde(rename="_id")]
    pub an_int: usize,
    pub a_string: String,
    pub a_list_ints: Vec<usize>
}


fn main() {

    let client = Client::connect("localhost", 27017)
        .ok().expect("Failed to initialize standalone client.");

    clear_db(&client.db("test"));

    let coll = client.db("test").collection("documents");

    initialize_data(&coll);

    let item = find_by_an_int(&coll, 5);

    println!("Retrieved Item: {:?}", item);

    find_by_an_int(&coll, 2);
    find_by_an_int(&coll, 1);
    find_by_an_int(&coll, 3);
}

fn clear_db(db: &Database) {
    db.drop_database().ok().expect("Failed to drop database");
}

fn initialize_data(coll: &Collection) {
    let sample_datas = vec![
        MyDocument { an_int: 1, a_string: "Hello".to_string(), a_list_ints: vec![1,2,3] },
        MyDocument { an_int: 2, a_string: "Hello".to_string(), a_list_ints: vec![1,2,3] },
        MyDocument { an_int: 3, a_string: "Hello".to_string(), a_list_ints: vec![1,2,3] },
        MyDocument { an_int: 4, a_string: "Hello".to_string(), a_list_ints: vec![1,2,3] },
        MyDocument { an_int: 5, a_string: "Hello".to_string(), a_list_ints: vec![1,2,3] }
    ];

    let sample_docs = sample_datas.iter().map(|data| dao_to_doc(data)).collect::<Vec<_>>();

    coll.insert_many(sample_docs, None).ok().expect("Failed to initialize data");
}

fn find_by_an_int(coll: &Collection, an_int: usize) -> MyDocument {
    let filter = doc! { "_id" => (an_int as i32) };

    let utc_before_find = UTC::now();
    let find_one_doc = coll.find_one(Some(filter), None).ok().expect("Failed to find_one").unwrap();
    let utc_after_find = UTC::now();

    println!("ms elapsed for find: {:?}", (utc_after_find - utc_before_find).num_milliseconds());

    doc_to_dao(find_one_doc)
}

fn dao_to_doc<T: Serialize>(item: &T) -> ::bson::Document {
    let bson = ::bson::to_bson(item).ok().expect("Couldn't serialize to doc");
    match bson {
        Bson::Document(d) => d,
        _ => panic!("Couldn't serialize to doc")
    }
}

fn doc_to_dao<T: Deserialize>(doc: Document) -> T {
    ::bson::from_bson(Bson::Document(doc.clone())).ok().expect("Couldn't deserialize to struct")
}
```

output (using --release flag):
```
ms elapsed for find: 0
Retrieved Item: MyDocument { an_int: 5, a_string: "Hello", a_list_ints: [1, 2, 3] }
ms elapsed for find: 38
ms elapsed for find: 40
ms elapsed for find: 39
```

As you can see, find_one is taking around 40ms. If I make 3 or 4 mongodb calls per request, this really adds up.  I was hoping my whole api could operate with elapsed times of under 20ms for most endpoints.

Is the library just slow? Is this the latency I should expect with mongo?  Can I do something to improve the time?

EDIT: I also find it interesting that once in a while, calls take 0ms:
> ms elapsed for find: 0

**Comment by saghm** [comment]
This definitely isn't because of Mongo itself; if you try out running the query on the Mongo command-line shell (`db.documents.find({ _id: 2 }).explain('executionStats')`), you'll see that it consistently runs more more quickly (running it locally on my machine with the same contents in the database, I haven't seen any execution time besides 0).

I'm sure that the driver could be optimized to reduce the latency, but there currently isn't anyone working on it (it's not officially supported by MongoDB, and I personally haven't had any time to work heavily on it recently). We were focusing on completeness rather than efficiency when writing this last summer, so if speed is a huge concern for you, it might make more sense to use one of the more mature drivers that Mongo officially supports (a list of which you can find [here](https://docs.mongodb.org/ecosystem/drivers/)).

**Comment by freiguy1** [comment]
Thanks for the quick and honest response!

**Comment by kyeah** [comment]
For anyone that needs better performance in a current rust app, take a look at the [Rust C-Wrapper](https://github.com/thijsc/mongo-rust-driver). It won't have the safety guarantees provided by a pure Rust implementation and is less feature-complete, but the performance will depend directly on the mature C driver.
