### ISSUE TITLE
GridFS `put_get` test failing on MongoDB 3.2

### ISSUE THREAD

**Issue by saghm** [mongodb-labs/mongo-rust-driver-prototype#144]
Travis seems to have reported an issue with the test [`v3_2::client::gridfs::put_get`](https://travis-ci.org/saghm/mongo-rust-driver-prototype/builds/126183253). I haven't been able to replicate it (i.e. all of the 3.2 tests seem to be working locally for me), but that may be because I have version 3.2.3 installed rather than 3.2.4 (Archlinux hasn't updated to the latest release, it seems; I'll download it manually shortly to see if I can replicate the issue with it).

@kyeah, I don't suppose you have any idea what's causing this? I'm not too familiar with the GridFS parts of the code, so any advice/expertise would be much appreciated!

**Comment by vkarpov15** [comment]
I'd try re-running it on travis, travis is wildly flakey and tests will often fail for no reason.

**Comment by saghm** [comment]
Yeah, that seemed to fix it. Not sure why I didn't try this first...
