### ISSUE TITLE
MapReduce support ?

### ISSUE THREAD

**Issue by zerosign** [mongodb-labs/mongo-rust-driver-prototype#146]
Is this crate does support mongodb map reduce support or only support Aggregation ? Since in https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/d36d71a2e82f65cf3e2344e4ffa71ce85d4ec0ac/src/command_type.rs, I don't see command type for map reduce in mongodb.

CMIIW

**Comment by saghm** [comment]
You're correct, we did not implement map reduce in the driver. From looking at the [documentation](https://docs.mongodb.org/manual/reference/command/mapReduce/), it seems like it would only require adding the new command type and a corresponding method to the `Collection` type. I'm going to have a lot of free time relatively soon, so if this would be useful for you, I might be able to take a stab at it within the next week or so. Alternately, if you happen to have the time and inclination, a PR would definitely be welcome as well!

**Comment by zerosign** [comment]
I'll try my best this weekend looking the docs and try implement it :+1:

**Comment by saghm** [comment]
I just opened a PR with an implementation of the map-reduce functionality. Feel free to give some feedback about the API defined in it (i.e. the methods defined in `coll/mod.rs`), since you'll probably be the first one to use it once it gets merged!

**Comment by zerosign** [comment]
Sorry, lately, I need to deal with something elses, I'll try to look the PR, thank you.

**Comment by saghm** [comment]
Given that aggregation is strongly preferred over the map reduce feature nowadays (and that it doesn't seem like there's a lot of demand for this feature), I'm going to close this issue.
