### ISSUE TITLE
Updating a date field

### ISSUE THREAD

**Issue by russoue** [mongodb-labs/mongo-rust-driver-prototype#150]
How do I do the equivalent of the following?

    > db.testusers.find()
    { "_id" : 1, "status" : "a", "lastModified" : ISODate("2016-05-13T04:54:57.384Z") }
    > db.testusers.update({ _id: 1 }, { $currentDate: { lastModified: true }})
    WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
    > db.testusers.find()
    { "_id" : 1, "status" : "a", "lastModified" : ISODate("2016-05-21T00:29:09.603Z") }

I tried it this way but failed:

        let update = doc!{ "$set" => { "foo" => fooval,
                                       "$currentDate" => {
                                           "created_at" => true,
                                           "last_updated_at" => true
                                       }
                                     }};
        let res = self.foo_collection.update_one(filter,
                                            update,
                                            Some(UpdateOptions {
                                                upsert: false,
                                                write_concern: None
                                            }));

**Comment by saghm** [comment]
I can't be sure about what went wrong without knowing what the exact error message is (and what the values of `fooval` and `filter` are), but you should be able to just put pass in the exact same document you used in the shell (i.e. `{ $currentDate: { lastModified: true }}` for the second argument.

On a tangential note, `upsert: false` and `write_concern: none` are the default options for update commands, so you can just pass in `None` as the third argument.

**Comment by russoue** [comment]
I tried to write a minimal program to demonstrate this:

    #[macro_use(bson, doc)]
    extern crate bson;
    extern crate chrono;
    extern crate mongodb;

    use bson::Bson;
    use chrono::*;
    use mongodb::{Client, ThreadedClient};
    use mongodb::db::ThreadedDatabase;

    fn main() {
        let client_in_res = Client::connect("localhost", 27017);
        if client_in_res.is_err() {
            panic!("Could not connect to the Mongodb: {}",
                client_in_res.err().unwrap());
        }
        println!("Connected to the Mongodb database");
        let client = client_in_res.unwrap();
        let db = client.db("test");
        let user_coll = db.collection("users");
        let utc: DateTime<UTC> = UTC::now();
        let bson_date = Bson::from(utc);
        let doc = doc!{"name" => "test_name",
                    "last_modified" => bson_date};
        let res1 = user_coll.insert_one(doc, None);
        println!("Insert result: {}", res1.is_ok());
        let filter = doc!{"name" => "test_name"};
        let update = doc!{"$set" => { "name" => "new_name",
                                        "$currentDate" => {
                                            "last_modified" => true
                                        }
                                    }
                        };
        let res2 = user_coll.update_one(filter, update, None);
        println!("Update result: {}", res2.is_ok());
    }

I see the following output if I run it:

    Connected to the Mongodb database
    Insert result: true
    Update result: true

On the `mongo` shell:

    > db.users.find()
    { "_id" : ObjectId("57410ab6643431ca0e49c886"), "name" : "test_name", "last_modified" : ISODate("2016-05-22T01:26:14.787Z") }

This shows even though the update operation returns `true` the update does not happen. Please help.

**Comment by saghm** [comment]
Again, I think you'd have to change the `update` argument to `{ $currentDate: { lastModified: true }}` rather than `{ $set: { $currentDate: { lastModified: true }}}`; you don't need to change it to use `$set` in the same way that you didn't use `$set` in the shell command you wrote in your initial comment.

For reference, I tested doing it this way with the following program (after inserting a document manually with `_id` 1 through the shell):

```rust
#[macro_use(bson, doc)]
extern crate bson;
extern crate mongodb;

use mongodb::{Client, ThreadedClient};
use mongodb::db::ThreadedDatabase;


fn main() {
    let client = Client::connect("localhost", 27017).unwrap();
    let db = client.db("test");
    let coll = db.collection("testusers");

    let filter = doc! { "_id" => 1 };
    let update = doc! {
        "$currentDate" => { "lastModified" => true }
    };

    coll.update_one(filter, update, None).unwrap();
}

**Comment by russoue** [comment]
I tried the following but this time the update is not only failing but also `update_one` is returning `false`, which is better I think:

```rust
#[macro_use(bson, doc)]
extern crate bson;
extern crate chrono;
extern crate mongodb;

use mongodb::{Client, ThreadedClient};
use mongodb::db::ThreadedDatabase;

fn main() {
    let client_in_res = Client::connect("localhost", 27017);
    if client_in_res.is_err() {
        panic!("Could not connect to the Mongodb: {}",
            client_in_res.err().unwrap());
    }
    println!("Connected to the Mongodb database");
    let client = client_in_res.unwrap();
    let db = client.db("test");
    let user_coll = db.collection("users");
    let filter = doc!{"name" => "test_name"};
    let update = doc!{"name" => "new_name",
                        "$currentDate" => {
                            "last_modified" => true
                        }
                        };
    let res2 = user_coll.update_one(filter, update, None);
    println!("Update result: {}", res2.is_ok());
}
```

Then I tried to update the date only:

```rust
let update = doc!{"$currentDate" => {"last_modified" => true}};
```

And it worked! Then after having a closer look I found what the problem was with my original code and I fixed it:

```rust
let update = doc!{"$set" => {"name" => "new_name2"},
                  "$currentDate" => {"last_modified" => true}};
```

The `$currentDate` element should be a top level one, it should not be a child of `$set`. I am closing the issue. Thanks a lot for helping!
