### ISSUE TITLE
Add documentation for how to run tests

### ISSUE THREAD

**Issue by saghm** [mongodb-labs/mongo-rust-driver-prototype#163]
#162 exposed a hole in our documentation when it comes to how to properly run our test suite. We should add something along the lines of a TESTING.md (and link to it in the README) detailing how to  properly run them to avoid more confusion.

**Comment by kyeah** [comment]
Makin' notes for later. This involves documentation on:

1. Setting up mongodb on 27017 and 27018
2. Initializing the json specs submodule (`git submodule update --init`)
3. Warning users that test databases are _not_ cleaned up
