### ISSUE TITLE
Fix your travis build for 1.0

### ISSUE THREAD

**Issue by zpallin** [mongodb-labs/mongo-rust-driver-prototype#170]
For 1.0, the travis build specifically states that this is not an active repository. Not to mention, I pulled and built 1.0 myself and it does in fact build.

Please fix as to not confuse people. :)

**Comment by saghm** [comment]
Thanks for letting us know! I'll look into why this happened, as it certainly was working in the past

**Comment by zpallin** [comment]
Ah you know what, I think that it says it's not active because you don't yet have a .travis.yml on master. The 1.0 branch looks good. Neato.
