### ISSUE TITLE
Documentation is 404

### ISSUE THREAD

**Issue by kpcyrd** [mongodb-labs/mongo-rust-driver-prototype#177]
Both links for documentation return a 404 ([github], [cargo.io])

[github]: http://mongodbinc-interns.github.io/mongo-rust-driver-prototype/
[cargo.io]: https://mongodb-labs.github.io/mongo-rust-driver-prototype/mongodb

Please fix it :)

**Comment by saghm** [comment]
Sorry about that! I'll get it fixed tomorrow. (I don't have ownership of the repository, so I'll need to talk to the people that do).

For now, you can either click on the "Docs" badge at the top of the README or go directly to [docs.rs/mongodb]. As of a couple months ago, all crates published to crates.io automatically get their documentation published to docs.rs, which is just another reason why Rust is Awesome (TM).

**Comment by kyeah** [comment]
Ala #182, we should also add a description for the repo.

**Comment by saghm** [comment]
I opened a ticket for this with (the Mongo office) IT last week. If you have a specific description in mind, I can update the ticket to request that as well.

If we do add a description, we should update the one in Cargo.toml to match it.

**Comment by kyeah** [comment]
cool, thanks @saghm 🙏

**Comment by saghm** [comment]
The link at the top of the repository has been changed.
