### ISSUE TITLE
upsert:true doesn't insert

### ISSUE THREAD

**Issue by kpcyrd** [mongodb-labs/mongo-rust-driver-prototype#178]
I'm really sure I'm doing something very wrong here, but I can't get `upsert` to work.

I don't get any error messages and update_one returns `Ok`, yet my document doesn't exist in my collection afterwards. Please point me to the right direction. :)

Cargo.toml
```toml
[package]
name = "upserter"
version = "0.1.0"
authors = ["user"]

[dependencies]
bson = "0.3.1"
mongodb = "0.1.8"
```

main.rs
```rust
#[macro_use(bson, doc)]
extern crate bson;
extern crate mongodb;

use mongodb::{Client, ThreadedClient};
use mongodb::db::ThreadedDatabase;
use mongodb::coll::options::*;

fn main() {
    let uri = "mongodb://example.com:27017";
    let client = Client::with_uri(uri)
        .ok().expect("failed to connect to database");

    let coll = client.db("inventory").collection("status");

    let name = "foo";
    let name_copy = name.clone();
    let var1 = 4;
    let var2 = 5;

    let zz = coll.update_one(doc!{
        "name" => name
    }, doc!{
        "$set" => {
            "name" => name_copy,
            "var1" => var1,
            "var2" => var2
        }
    }, Some(UpdateOptions {
        upsert: true,
        write_concern: None
    }));

    match zz {
        Ok(x) => {
            println!("success(acknowledged):    {:?}", x.acknowledged);
            println!("success(matched_count):   {:?}", x.matched_count);
            println!("success(modified_count):  {:?}", x.modified_count);
            println!("success(upserted_id):     {:?}", x.upserted_id);
            println!("success(write_exception): {:?}", x.write_exception);
         },
        Err(err) => println!("{:?}", err),
    };
}
```

output
```
$ cargo run
   Compiling upserter v0.1.0 (file:///.../upserter)
    Finished debug [unoptimized + debuginfo] target(s) in 1.35 secs
     Running `target/debug/upserter`
success(acknowledged):    true
success(matched_count):   0
success(modified_count):  0
success(upserted_id):     None
success(write_exception): None
$
```

**Comment by saghm** [comment]
I'm not able to reproduce this; when I run it locally, the upsert occurs. Can you double check that you're connecting to the right mongod and that you're checking the right database and collection for the new document?

**Comment by kpcyrd** [comment]
I found the issue, I'm running mongodb from debian stable, which is `v2.4.10`, while the readme says:

> Note: This driver currently only supports MongoDB 3.0.x and 3.2.x. This driver is not expected to work with MongoDB 2.6 or any earlier versions. Do not use this driver if you need support for other versions of MongoDB.

Querying information was working fine, while update seems to fail silently.

So, my fault, sorry for the noise :)

**Comment by saghm** [comment]
No worries! If you're interested in trying out the latest version, MongoDB hosts a third-party repo you can use: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/
