### ISSUE TITLE
3.4 compatibility

### ISSUE THREAD

**Issue by saghm** [mongodb-labs/mongo-rust-driver-prototype#179]
A few new features were added to MongoDB in 3.4 which we haven't implemented support for yet. The release notes of 3.4 are [here](https://docs.mongodb.com/manual/release-notes/3.4/), but not everything there requires a change in drivers. Off the top of my head, I know that views, the decimal type, and likely collations will require additions/changes to the code.

Additionally, three tests currently fail when run against 3.4. Two of them (`apm::logging` and `client::db::create_collection` seem to be due to the same issue, namely an option that no longer seems to be supported, and the other (`client::db::create_and_get_users`) seems like it might be an issue with the ordering of the results. I'm guessing all of these are issues with the tests rather than the actual driver; if this is the case, we'll likely have to do the same kind of fix we did with 3.0 vs.3.2.

**Comment by saghm** [comment]
Progress update: #185 fixed a number of the issues the driver had with 3.4.x and fixed all of the tests failing except for `client::db::create_and_get_users`. We'll still have to add views, collations, and the decimal type, the last of which will probably only require changes to `bson` (https://github.com/zonyitoo/bson-rs/issues/53).

**Comment by saghm** [comment]
Another update (because I forgot to reference this issue in the PR): #188 fixed the tests for 3.4, so that leaves only implementing the new features.

**Comment by Iulian7** [comment]
Is there any progress on these features?

**Comment by saghm** [comment]
Unfortunately there hasn't been yet. I hope to find some time soon to dig through the backlog of features we have planned for this driver.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!
