### ISSUE TITLE
Remove rustc_serialize dependency, Upgrade bson lib

### ISSUE THREAD

**Issue by kyeah** [mongodb-labs/mongo-rust-driver-prototype#186]
:wave: we should move over to using `serde_json` and `data-encoding` like the bson lib, then upgrade that dependency and shuttle out `rustc_serialize` since it's not really being maintained anymore. See https://github.com/zonyitoo/bson-rs/pull/54.

**Comment by zonyitoo** [comment]
@kyeah Please upgrade `bson` to `v0.4.2`. I found that your PR has been reverted by another PR... I have already fixed it and released with `v0.4.2`, please upgrade.

**Comment by kyeah** [comment]
yeah! those changes to bson break the mongo build, so I'll work on this over the weekend.
