### ISSUE TITLE
Serde and BSON release

### ISSUE THREAD

**Issue by ThetaSinner** [mongodb-labs/mongo-rust-driver-prototype#203]
BSON version is now 0.7, which has changes for compatibility with Serde 1.0

I was moving my project onto Serde 1.0 which meant upgrading BSON to the latest version too, due to breaking changes in the Serde release. Unforunately this is not compatible with the version this crate uses.

Normally I would be happy just using an old release of Serde for now. But I've been able to take Serde updates up until now and I'm concerned about how long I'll end up staying on this version because of this dependency.

**Comment by saghm** [comment]
Hi, and thanks for opening the issue! I'll test the driver with the updated `bson` and `serde_json` dependencies, and assuming it all works, I'll push a new version shortly.

**Comment by saghm** [comment]
Just published 0.2.7, which updates `bson` to 0.7.0 and `serde_json` to 1.0.0. Thanks again for the report!

**Comment by ThetaSinner** [comment]
Awesome, thanks for the update and the quick response time!
