### ISSUE TITLE
Auth failed

### ISSUE THREAD

**Issue by Matrix-Zhang** [mongodb-labs/mongo-rust-driver-prototype#204]
```
#[macro_use]
extern crate bson;
extern crate mongodb;

use mongodb::connstring::{ConnectionString, parse};
use mongodb::{Client, ClientOptions, ThreadedClient};
use mongodb::db::ThreadedDatabase;

fn main() {
    let config = parse("mongodb://username:password@hostname:27017")
        .unwrap();

    let client = Client::with_config(config, None, None).unwrap();

    let db = client.db("my_db");
    let coll = db.collection("stuff");
    let doc = doc! { "x" => 1 };
    coll.insert_one(doc, None).unwrap();
}
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OperationError("not authorized on my_db to execute command { insert: \"stuff\", documents: [ { x: 1, _id: ObjectId(\'58fdbd66613132df407d8766\') } ] }")', /checkout/src/libcore/result.rs:859

i am very sure the usename and password is correct, and the user have read write permission with the data base

**Comment by saghm** [comment]
Hi, thanks for the report! We haven't implemented authenticating through the URI in this driver yet; you'll need to use [`Database::auth`](https://docs.rs/mongodb/0.2.6/mongodb/db/trait.ThreadedDatabase.html#tymethod.auth).

If you change your code to the following, does it work?

```rust
#[macro_use]
extern crate bson;
extern crate mongodb;

use mongodb::connstring::{ConnectionString, parse};
use mongodb::{Client, ClientOptions, ThreadedClient};
use mongodb::db::ThreadedDatabase;

fn main() {
    let client = Client::connect("hostname", 27017).unwrap()
    let db = client.db("my_db");
    db.auth("username", "password");

    let coll = db.collection("stuff");
    let doc = doc! { "x" => 1 };
    coll.insert_one(doc, None).unwrap();
}
```

**Comment by Matrix-Zhang** [comment]
it's ok!

**Comment by saghm** [comment]
Awesome! I'm going to close this issue then, but if you run into any other issues with the driver, feel free to file another issue!
