### ISSUE TITLE
IoError : failed to fill whole buffer

### ISSUE THREAD

**Issue by YjyJeff** [mongodb-labs/mongo-rust-driver-prototype#212]
Hi, I want to query data from mongo db. Here is my code:
`let client = Client::connect("localhost", 27017).expect("Failed to connect!!");
  let coll = client.db(DB).collection(COLLECTION);
  let doc = doc! {"key" => name};
  let mut cursors = coll.find(Some(doc), None).unwrap();
  // process data
  .......
`

I put all of this code in a function and spawn a thread to execute it. It almost works well. But sometimes(spawns many threads) the last sentence will panic even if I query a valid data:

`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error│Transforming org.ice4j.TransportAddress...
 { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buf│Transforming org.ice4j.ResponseCollector...
fer") }) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/re│Transforming org.ice4j.attribute.XorOnlyAttribute...
sult.rs:868`
Why does it panic?  How to fix it? Thanks!

**Comment by saghm** [comment]
For future reference, did you close this because you determined it to be to running out of clients in the pool (i.e. #213)?

**Comment by YjyJeff** [comment]
@saghm Yep, I decided to share one client through all of my threads. It goes well.
