### ISSUE TITLE
Should have a method for listing index models.

### ISSUE THREAD

**Issue by thedodd** [mongodb-labs/mongo-rust-driver-prototype#224]
Currently there is a method for [listing indices on a collection](https://docs.rs/mongodb/0.3.0/mongodb/coll/struct.Collection.html#method.list_indexes), which returns a `Result<Cursor<bson::ordered::OrderedDocument>>`. This is great, however it would be awesome to have a method which returns `Result<Cursor<IndexModel>>` for interoperability with the other index methods dealing with `IndexModel`.

I'm happy to open a PR for this as well.

**Comment by saghm** [comment]
Feel free to open a PR! Our cursor type isn't generic (as Iterator types in Rust use associated types rather than generics), so Cursor<IndexModel> isn't quite the right type, so I think the right way to go might be to create an IndexModelIterator type that wraps cursor.
