### ISSUE TITLE
Authentication with uri failed

### ISSUE THREAD

**Issue by max-frai** [mongodb-labs/mongo-rust-driver-prototype#230]
Hello, I have user with `root` permissions added into `admin` db. So when I connect to mongodb via some gui tool I just put ip address, user: "admin", password: "somepwd". It works great.
Now I want to connect in rust code:
 `Client::with_uri("mongodb://admin:somepwd@IPADDRESS:27017/admin")`  and later when I chose some exact db and trying to find something in collection I get `not authorized for query on DB.COL` error.

When I tried non-uri auth:
```
    let client = Client::connect(IPADDRESS, 27017).unwrap();
    let db = client.db("admin");
    let auth_result = db.auth("admin", "somepwd");
    client.db("real-work-db")
    ...
```
it works great.

**Comment by saghm** [comment]
Hi! We haven't currently implemented any of the URI options beyond the hostname and port, so using the `auth` method on `Database` is the only way to authenticate. We're planning to add eager authentication, as discussed in #205; would this be sufficient for your use cases, or do you specifically need URI configuration?

**Comment by max-frai** [comment]
Thanks for the reply.
No problem, I just spent some time until realized how to make it work :)
Using auth directly is ok

**Comment by saghm** [comment]
Awesome! I'll close this issue then, but feel free to reopen it or file a new issue if you have problems again!
