### ISSUE TITLE
Reference cycle of `Client` and `Monitor` leaks connection

### ISSUE THREAD

**Issue by stefano-pogliani** [mongodb-labs/mongo-rust-driver-prototype#247]
There seems to be a connection leak when creating a `Client`:
```rust
extern crate mongodb;
use mongodb::Client;
use mongodb::ThreadedClient;

fn main() {
  let client = Client::connect(host, port).unwrap();
  // This will print 2 instead of 1.
  println!("{}", std::sync::Arc::strong_count(&client));
}
```

I believe this is caused by the `Monitor` instance stored in the `Server` instances that are added to the `Topology` stored in the `Client`:

  * [Once the client is created the servers are added](https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/master/src/lib.rs#L387)
  * [Each server keeps a reference to a monitor](https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/0f348beb955a9d645d25c854ff5aff149befc526/src/topology/server.rs#L89)
  * [The monitor holds the client for when it refreshes the topology](https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/0f348beb955a9d645d25c854ff5aff149befc526/src/topology/monitor.rs#L71)

I would be happy to open a Pull Request to change the `Client` to a `std::sync::Weak<ClientInner>`.
With this change the cycle is broken but it means adding two `self.client.upgrade().unwrap()` to:

  * https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/0f348beb955a9d645d25c854ff5aff149befc526/src/topology/monitor.rs#L272
  * https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/0f348beb955a9d645d25c854ff5aff149befc526/src/topology/monitor.rs#L329

Would this approach be acceptable?

**Comment by nico-abram** [comment]
Is this still a thing? Is the explanation still accurate?

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
