### ISSUE TITLE
Add auth to base examples

### ISSUE THREAD

**Issue by marcelbuesing** [mongodb-labs/mongo-rust-driver-prototype#256]
This might be common knowledge but I was not aware that there was the need for calling auth with user and password after already providing it via uri already.

So:
```
let client = Client::with_uri("mongodb://x:y@localhost:27017")?;
```
turned out to be
```
let client = Client::with_uri("mongodb://x:y@localhost:27017")?;
client.auth("x", "y");
```

Is this a bug or am I missunderstanding user and pass in the uri ?

**Comment by kyeah** [comment]
Thanks for the issue! user-password authentication occurs at the database-level. The user, password, and database are parsed from the URI, but I don't believe we have it set up to automatically authenticate when you create the database object, which is probably desirable from a user standpoint.

**Comment by HugoSanchez** [comment]
Hi, 

I get:

`No method named 'auth' for found type 'std::sync::Arc::<mongodb::ClientInner>' in the current scope`.

I'm also not able to use '?' in the previous line were I connect 'with_uri'.

What am I missing here?

**Comment by jcdyer** [comment]
Sorry this is a year late, but for posterity, auth is on the db object.  So try:  

```rust
let db = client.db("appdb")?;
db.auth("x", "y")?;
```
You can only use `?` in functions that return `Result<T, E>`.  If you are in a function that returns something else, you'll need to handle the error yourself.  The most flexible way is:

```rust
let db = match client.db("appdb") {
    Ok(db) => db,
    Err(err) => /* Do something else */
};
if let Err(err) => db.auth("username", "password") {
    eprintln!("Could not authenticate: {:?}", err)
}
```
If all you want to do is exit the program when something fails, you can do:

```rust
let db = client.database("appdb").expect("could not connect to database appdb");
db.auth("username", "password").expect("could not authenticate to database appdb");
```

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!
