### ISSUE TITLE
Error `Update only works with $ operators.` on `update_one`

### ISSUE THREAD

**Issue by kper** [mongodb-labs/mongo-rust-driver-prototype#264]
Hi!

I'm having some troubles performing updates like it is described on the mongodb blog post (https://www.mongodb.com/blog/post/the-new-mongodb-rust-driver).

Do I miss something, because I'm getting `Update only works with $ operators.` as an error?

> let film_a = doc!{ "title" => "Ferris Bueller’s Day Off" };
> 
> // Update a single document.
> let filter = film_a.clone();
> let update = doc!{ "director" => "John Hughes" };
> 
> // Update a film with director information.
> coll.update_one(filter, update, None)
>     .ok().expect("Failed to update document.");

Minimal Example:

Cargo.toml:
```
[package]
name = "mongo_minimal"
version = "0.1.0"
authors = ["Kevin Per <kevp.per@gmail.com>"]


[dependencies]
mongodb = "0.3.9"
bson = "0.12.1"
serde = "1.0"
serde_derive = "1.0"
```

main.rs:
```
#[macro_use(bson, doc)]
extern crate bson;
extern crate mongodb;
#[macro_use]
extern crate serde;
#[macro_use]
extern crate serde_derive;

use bson::Bson;
use mongodb::{Client, ThreadedClient};
use mongodb::db::ThreadedDatabase;

#[derive(Debug, Serialize, Deserialize)]
struct Game {
    members: String
}

fn main() {
    let client = Client::connect("localhost", 27017)
        .expect("Failed to initialize standalone client.");

    let coll = client.db("test").collection("games");

    //Finding doc
    let doc = coll.find_one(Some(doc! { "_id": bson::oid::ObjectId::with_string("5b4502ccc0a5c226c94e07d4").unwrap() }), None)
    .expect("Document not found");

    //Update model
    let mut de_game: Game = bson::from_bson(bson::Bson::Document(doc.unwrap())).unwrap();

    de_game.members = "test".to_string();

    let filter = doc! {
        "_id": bson::oid::ObjectId::with_string("5b4502ccc0a5c226c94e07d4").expect("invalid token")
    };

    let ser_game = bson::to_bson(&de_game).unwrap();

    //Update db
    if let bson::Bson::Document(document) = ser_game {
        coll.update_one(filter, document, None).unwrap();
    }
    else {
        panic!("Something went wrong");
    }
}
```

Query:
`
db.games.insert({members:""})`

**Comment by saghm** [comment]
Looks like a mistake in the blog post! The correct way to do an update for a single field is to use `$set`, i.e. `doc! { "$set": { "title": "Ferris Bueller’s Day Off" } }`. Alternately, you can replace the entire document by using `replace_one` instead of `update_one`.

**Comment by kper** [comment]
Thanks for the clarification!
