### ISSUE TITLE
Connection Issue with MongoDB 4.0.x?

### ISSUE THREAD

**Issue by nevi-me** [mongodb-labs/mongo-rust-driver-prototype#273]
I've been developing an application with this driver on 3.6. I'm running 4.0 in production. Both my development and prod environments run replica sets.

I'm getting `OperationError("No servers available for the provided ReadPreference.")` when connecting in prod.

From looking at MongoDB logs, I see:

```
2018-09-14T19:33:55.431+0000 I NETWORK  [listener] connection accepted from 10.0.1.1:45726 #426 (110 connections now open)
2018-09-14T19:33:55.432+0000 I NETWORK  [conn426] received client metadata from 10.0.1.1:45726 conn426: { driver: { name: "mongo-rust-driver-prototype", version: "0.3.10" }, os: { type: "linux", architecture: "x86_64" } }
2018-09-14T19:33:55.432+0000 I NETWORK  [listener] connection accepted from 10.0.1.1:45728 #427 (111 connections now open)
2018-09-14T19:33:55.432+0000 I NETWORK  [conn427] received client metadata from 10.0.1.1:45728 conn427: { driver: { name: "mongo-rust-driver-prototype", version: "0.3.10" }, os: { type: "linux", architecture: "x86_64" } }
...
2018-09-14T19:34:05.476+0000 I NETWORK  [conn426] end connection 10.0.1.1:45726 (110 connections now open)
2018-09-14T19:34:05.476+0000 I NETWORK  [conn427] end connection 10.0.1.1:45728 (109 connections now open)
```

I've got 2 connections in 2 threads, they seem to get created, then they disconnect 10 seconds after.

I connect thus:

```rust
    let mut options = ClientOptions::new();
    options.read_preference = Some(ReadPreference::new(ReadMode::PrimaryPreferred, None));
    let mongo_uri = env::var("MONGO_URI").unwrap();
    let client = Client::with_uri_and_options(&mongo_uri, options).expect("Failed to connect");
```

Where `MONGO_URI` is `mongodb://host:port/db` with no connection options.

It's a bit of effort to get a test 3.6 replica set running, so I wanted to first find out if there's any known issues with this driver not working with 4.0?

**Comment by saghm** [comment]
The test suite is being run on Travis against 4.0 without any issues; trying it out locally, it works fine for me. Are you running using PrimaryPreferred with a non-replica set?

**Comment by nevi-me** [comment]
I've got a 1-member replica set (mainly so I can tail oplog). I encountered the problem before I chose PrimaryPreferred, I'll try other combinations and revert back with some feedback.

**Comment by nevi-me** [comment]
Connecting directly with `Client::connect("host", port)` worked. I did check my `rs.status()` to check if there's issues with my replica set, but all seems fine there.

I don't know how to get more debug information, but if there isn't enough information to figure out what the cause is, I can close the issue.

**Comment by saghm** [comment]
I wrote a small example based off your snippet to try see if I could reproduce your issue (note that it drops the `foo.bar` collection, so be careful if you run it against your actual cluster):

```rust
#[macro_use]
extern crate bson;
extern crate mongodb;

use mongodb::{Client, ClientOptions, ThreadedClient, db::ThreadedDatabase, common::{ReadPreference, ReadMode}};

fn main() {
    let mut options = ClientOptions::new();
    options.read_preference = Some(ReadPreference::new(ReadMode::PrimaryPreferred, None));

    let client = Client::with_uri_and_options("mongodb://localhost:27017/foo", options).unwrap();
    let coll = client.db("foo").collection("bar");
    coll.drop().unwrap();

    coll.insert_one(doc! { "x": 1 }, None).unwrap();

    for doc in coll.find(None, None).unwrap() {
        println!("{}", doc.unwrap());
    }
}
```

It works fine for me both with a standalone and a single-node replica set with server version 4.0. I'm not sure what else to do to try to reproduce it, unless you have any ideas.

**Comment by stefano-pogliani** [comment]
I'm having this issue when attempting to connect to a mongos process.
I have tried using this with 3.4 and 3.6 and it seems to work fine but with 4.0 I get
```
No servers available for the provided ReadPreference.
```
I am not explicitly setting the read mode to anything.
Is there anything I can do to debug this?

**Comment by nevi-me** [comment]
Hi @stefano-pogliani, I've been unable to find out more information from my end. Can you check how long the connection stays open for on your mongo logs? Mine was just over 10s each time. I want to see if there's a pattern there.

**Comment by saghm** [comment]
Hi @stefano-pogliani! Can you provide an example of some code that runs fine on 3.4 and 3.6 but not on 4.0 along with the structure of your cluster (number of config servers, mongos's, and the number/composition of each shard)?

**Comment by stefano-pogliani** [comment]
Hi @saghm, sorry for the vague comment yesterday.
Here are some more details:

  * The mongo cluster is a docker-composed testing/developing setup: https://github.com/replicante-io/playgrounds/blob/86265d6198fb0778820ddadbacb1611cd1e86ecd/mongo/sharded/docker-compose.yml
  * The mongo cluster is: 1 3-nodes config replica set, 2 3-nodes shard replica sets, 1 mongos instance
  * The code that creates the client is here: https://github.com/replicante-io/agents/blob/207670de0a2b0a6dd16f69ceeda1d14a8f6f28d9/mongodb/src/version/mod.rs#L51-L61
  * An example use of the client is here: https://github.com/replicante-io/agents/blob/207670de0a2b0a6dd16f69ceeda1d14a8f6f28d9/mongodb/src/version/v3_2/common.rs#L63-L67
  * The URI is used for the connection is: `mongodb://node:27017/` (where `node` is a docker container link to the mongos instance).

For context: the code is part of a monitoring/automation agent to be.
As such I needed the client to connect to the specifically to the given node and not any one node in the cluster/replica set.
To achieve this I explicitly set the topology to single.
This evening I will try removing the explicit topology settings and see if that makes a difference.

**Comment by stefano-pogliani** [comment]
More details:

  * Exact mongos version: v4.0.2
  * I get the error message in mongos logs constantly (as if the client was attempting a new connection just as the old one fails:
```
mongos_1      | 2018-09-20T18:21:30.252+0000 I NETWORK  [listener] connection accepted from 172.64.0.33:51291 #14252 (1 connection now open)
mongos_1      | 2018-09-20T18:21:30.253+0000 I NETWORK  [conn14252] end connection 172.64.0.33:51291 (0 connections now open)
mongos_1      | 2018-09-20T18:21:30.255+0000 I NETWORK  [listener] connection accepted from 172.64.0.33:51293 #14253 (1 connection now open)
mongos_1      | 2018-09-20T18:21:30.256+0000 I NETWORK  [conn14253] end connection 172.64.0.33:51293 (0 connections now open)
mongos_1      | 2018-09-20T18:21:30.258+0000 I NETWORK  [listener] connection accepted from 172.64.0.33:51295 #14254 (1 connection now open)
mongos_1      | 2018-09-20T18:21:30.258+0000 I NETWORK  [conn14254] end connection 172.64.0.33:51295 (0 connections now open)
```
  * Changing the client instantiation code to `let client = Client::connect("172.64.0.40", 27017)` seems to have slowed down the amount of logs in mongos (possibly because I set a server selection timeout which is different to the default)

I'm not sure it makes a difference but my setup (a local development environment) the MongoDB processes are all part of a docker network.
I have tried with the client both on the host and in a container in the same network.

**Comment by stefano-pogliani** [comment]
Oh, just spotted this: if I stop the client process and let the mongos process run with no connections for a while (at least 10 minutes) the mongos instance seems to get into an odd state where it would not accept connections (not even from a local `mongo` shell) and times out the docker compose stop command.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
