### ISSUE TITLE
IndexOptions.storage_engine appears to have an incorrect type.

### ISSUE THREAD

**Issue by thedodd** [mongodb-labs/mongo-rust-driver-prototype#282]
Hey guys, I hope all is well.

I've been in the process of building [wither](https://github.com/thedodd/wither) version `0.6.0`, implementing a custom derive for creating models. [PR is here](https://github.com/thedodd/wither/pull/16) for reference.

During the process, I've written extensive tests for the index system. I've discovered that the [IndexOptions.storage_engine](https://docs.rs/mongodb/0.3.10/mongodb/coll/options/struct.IndexOptions.html#structfield.storage_engine) field is of type `Option<String>`, but mongo appears to be expecting a BSON document & [the docs seem to corroborate this](https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/#ensureindex-options). To be sure, I also tried embedding a JSON document inside of a string and passing that as the value, but I ended up getting the same error. Here is the error I'm seeing:

```rust
DefaultError("Failed to create index: \"storageEngine\" options must be a document if present")
```

As the data type determines what is sent across the wire, there doesn't seem to be a workaround. We'll have to update the data type.

Please let me know if I am missing or overlooking anything, and thanks for all the work on this crate! Cheers!

**Comment by kyeah** [comment]
Thanks for the report and patience, @thedodd! Your assessment looks correct, this should be an optional document.
