### ISSUE TITLE
find is not working

### ISSUE THREAD

**Issue by johnkarasev** [mongodb-labs/mongo-rust-driver-prototype#285]
Hello the current find function is not working : 

![notworking](https://user-images.githubusercontent.com/37842273/47693164-d130cd00-dbb5-11e8-8008-d36b34107a51.jpeg)
 Its giving me 
13 |     match coll.find(Some(doc.clone()), None) {
   |                          ^^^^^^^^^^^ expected struct `bson::ordered::OrderedDocument`, found a different struct `bson::ordered::OrderedDocument`

which does not make any sense

**Comment by thedodd** [comment]
Hey @johnkarasev, you should have a look at #281. That’s the problem (or part of it, at least). 

Easiest way to fix:
- check the version of the bson crate that is required by the mongodb crate in your Cargo.lock. 
- update your Cargo.toml to have an exact version requirement on the version of bson that you discover from the above step. 

That should do the trick.

**Comment by johnkarasev** [comment]
Thanks! that solved the issue.

**Comment by stivenson** [comment]
> Hey @johnkarasev, you should have a look at #281. That’s the problem (or part of it, at least).
> 
> Easiest way to fix:
> 
>     * check the version of the bson crate that is required by the mongodb crate in your Cargo.lock.
> 
>     * update your Cargo.toml to have an exact version requirement on the version of bson that you discover from the above step.
> 
> 
> That should do the trick.

Gracias, funcionó.
