### ISSUE TITLE
Some connection URIs are not supported

### ISSUE THREAD

**Issue by cubetastic33** [mongodb-labs/mongo-rust-driver-prototype#291]
Connection URIs to MongoDB Atlas that start with `mongodb+srv://` don't work, and even with `mongodb://`, supplying connection options there in the URI doesn't to work. My connection URI looks like this: `mongodb://<USERNAME>:<PASSWORD>@<SECONDARY SERVER>,<PRIMARY SERVER>,<SECONDARY SERVER>/test?ssl=true&replicaSet=<SOME STUFF>&authSource=admin&retryWrites=true`. This doesn't work, and I was told that I'm supposed to specify the connection options using `ClientOptions`, but I don't know how.

**Comment by cubetastic33** [comment]
Okay, but what is the `ca_file`? Where do I get that? Why do I need that?

**Comment by cubetastic33** [comment]
Also, what connection string should I use if it shouldn't have the username and password? Both the connection URIs provided in the Atlas interface have usernames and passwords in them...

**Comment by saghm** [comment]
Apologies if I was unclear about the CA file; the Rust driver currently requires one, but Atlas expects the driver to just use the system CA. I've opened [this pull request](https://github.com/mongodb-labs/mongo-rust-driver-prototype/pull/292#pullrequestreview-175164993) to fix that bug in the API, and I'll follow-up here when it lands.

As for the authentication info, I believe that (once the aforementioned PR is merged), it should work if you remove the `<username>@<password>` substring from the (non-srv) URI and then manually pass them in as arguments to `Database::auth` (as described above) before doing anything with the client.

**Comment by cubetastic33** [comment]
So, atm, what's the workaround to these issues?

**Comment by cubetastic33** [comment]
I tried using a CA file and authenticating later - [here](https://paste.rs/jZj.rs) is my code, but it still doesn't work (same error)

**Comment by saghm** [comment]
The CA file should be the path to the CA file, not the contents of it.

**Comment by cubetastic33** [comment]
@saghm I still get the same error...

**Comment by saghm** [comment]
I just published version 0.3.12, which has support for using the system CA instead of specifying your own. Can you try that out and see if it works?

**Comment by cubetastic33** [comment]
@saghm Also, what all does the new version fix? Does it allow authentication from the connection URI?

**Comment by cubetastic33** [comment]
Yaaaaay! I managed to get it working now, but I had to authenticate on `client.db("auth")`, not `client.db("<my database name>")`. I got the idea when connecting using MongoDB Compass Community... Thanks a lot for your help!

**Comment by saghm** [comment]
Awesome! For future reference, "<my database name>" is just the name of the database the user is stored in.

**Comment by tony-cox** [comment]
Without this discussion, I doubt I would have worked out how to connect to Atlas.  I've added the following summary.  Is there any way we can either get this up on the docs for the crate or better yet have Atlas themselves give a connection string and example for Rust?  I gather the latter is unlikely while this is an unsupported driver, but it would be nice.

- Use the old C driver connection string supplied by Atlas (with `mongodb::` scheme, not `mongodb+srv` as specified by the new C driver strings)
- Cut the `<username>:<password>@` out of your connection string, leaving the rest
- Use ClientOptions::with_unauthenticated_ssl(None, false) to connect using SSL using the system CA
- Use Client::with_uri_and_options(CONNECTION_STRING, options) to create client
- To authenticate, use Database::Auth _on the database the user is stored in_.  For me this was "admin" and for the OP it was "auth".  It will be a db that Atlas has already made for you.
