### ISSUE TITLE
Problems with Authentication

### ISSUE THREAD

**Issue by goriunov** [mongodb-labs/mongo-rust-driver-prototype#293]
Hi i am trying to connect to the Atlas MongoDB (using your latest changes branch with a way to do not pass CA)

Code example:
``` rust
let mut options = ClientOptions::with_unauthenticated_ssl(None, false);
  options.read_preference = Some(ReadPreference::new(ReadMode::SecondaryPreferred, None));

  let client = Client::with_uri_and_options(
      "mongodb://cluster-shard-00-00:27017,cluster-shard-00-01:27017,cluster-shard-00-02:27017/test?replicaSet=Cluster-shard-0",
      options
    )
    .unwrap();

  let mut db = client.db("my_super_db");
  db.auth("user", "password").unwrap();
```

how ever i am always getting this error: 
```
 on an `Err` value: OperationError("Authentication failed.")'
```

I have tried many different ways to change url and created different users a well how ever there is always two diffferent errors one is  `Authentication failed.` and sometimes i get `No servers available for the provided ReadPreference.`  second one only happens when i dont  use `with_unauthenticated_ssl`.

**Comment by max-frai** [comment]
I had same issue but with 0.3.12 everything works okay.

**Comment by goriunov** [comment]
@max-frai how do u structure url and does it work on fee cluster?  I have spent lots of time and could not make it work.

**Comment by arpitsr** [comment]
Same issue here anyone has working version and example of mongodb atlas connection with rust driver

**Comment by thedodd** [comment]
@goriunov also, just curious, it looks like the replicaset name specific in the example above is `replicaSet=Cluster-shard-0` ... are you sure that is correct and that it shouldn't be `cluster-shard-0` with lowercase? TBH, I'm not 100% sure that would make a difference, but often times it is the smallest of things.

**Comment by max-frai** [comment]
@thedodd Hi! 
I had simple hetzner server with one mongodb instance. So fallback to `0.3.10` helped me. But now I'll try again on the latest version

**Comment by goriunov** [comment]
@thedodd i simply  created free Atlas Mongo account with all default settings and  added user then copied url from there (removing username and password from url and moving it to the auth method)

**Comment by thedodd** [comment]
@goriunov ok! I’ll set one up and experiment. 

Also, this may be related, I have observed that this client has issues with connecting to sharded clusters. I’ve haven’t looked into this yet, but I did open an issue for it a while back. 

Do you know if the free atlas mongo is sharded or goes through a mongos???

**Comment by goriunov** [comment]
@thedodd if i remember correctly it is sharded.

**Comment by jjgumucio** [comment]
Any update on this issue? I'm having the same problem...

**Comment by thedodd** [comment]
Unfortunately not yet. This driver has some issues with connecting to sharded clusters, I've run into the issue as well. I hope I'll be able to get some time to hack on it, but I just recently started a new gig, so I don't want to make any promises.

**Comment by punkdata** [comment]
Any update on this issue?

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
