### ISSUE TITLE
Driver suggestions for rust project

### ISSUE THREAD

**Issue by mezeipetister** [mongodb-labs/mongo-rust-driver-prototype#297]
Hi Guys,

I will start an e-commerce project and we would like to use MongoDB and rust. Do you have any advice which driver should I start to use?

Thank you in advance,
Peter.

**Comment by thedodd** [comment]
@mezeipetister sorry for the late response here. Yea, this driver will treat you pretty well. I would recommend it. 

If you guys are into modeling your data, I would also recommend that you check out the [wither project](https://github.com/thedodd/wither) as well. It is built upon this driver and offers a lot of convenience and simplicity. You always have a handle to the underlying driver as well, if you need it.

Any major constraints that would influence your decision. Happy to help evaluate.

**Comment by thedodd** [comment]
@mezeipetister keep me in the loop. If you have resolved your questions and such, mind closing this issue?

**Comment by jjgumucio** [comment]
@thedodd Could you provide an example for DB authentication please?

I've tried to use db.auth() but I get this error:
`Could not authenticate to DB: OperationError("No servers available for the provided ReadPreference.")`

Any help would be appreciated!

**Comment by thedodd** [comment]
@jjgumucio normally I would just construct a [valid MongoDB URL](https://docs.mongodb.com/manual/reference/connection-string/) which includes the credentials you are using. I've had good success with that in the past. You will just want to ensure that the credentials you present are valid for the DB you are connecting to.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
