### ISSUE TITLE
[Ask]: using $in doc!

### ISSUE THREAD

**Issue by deltavin** [mongodb-labs/mongo-rust-driver-prototype#298]
I am trying to use $in to find documents. In the following example, I'm trying to get documents where category is either "news" or "politics". 

**Attempt 1: fails**
using a vector of categories:
```
let cats: Vec<&str> = vec!["news", "politics"];
let cursor = collection.find(Some(doc! {"categories": {"$in": cats}}),None,);
```

This fails to compile, saying: the trait bound `mongodb::Bson: std::convert::From<std::vec::Vec<&str>>` is not satisfied

**Attempt 2: fails**
Instead of a vector, use an array:
```
let cats = ["news", "politics"];
let cursor = collection.find(Some(doc! {"categories": {"$in": cats}}),None,);
```
This also fails to compile saying: the trait bound `mongodb::Bson: std::convert::From<[&str; 2]>` is not satisfied

**Attempt 3: passes**
hard-code the array in the query:
```
let cursor = collection.find(Some(doc! {"categories": {"$in":  ["news", "politics"]}}),None,);
```
This works

**Question**
What is the right way to use $in or any such operator that expects a collection of strings. Thanks

Edit:
Based on the error message, here's what I ended up doing to make it work:
```
let cats: Vec<Bson> = some_str.split(",").collect::<Vec<&str>>().into_iter().map(|i| Bson::from(i)).collect();
let cursor = collection.find(Some(doc! {"categories": {"$in": cats}}),None,);
```

Let me know if there's a better way around this, otherwise, you may close/remove the post.
thanks

**Comment by thedodd** [comment]
Hey, sorry for the super late response. I’ll take a look at this ASAP and see if we can get this resolved.

**Comment by thedodd** [comment]
@deltavin hey, so based on your comments above, looks like **option 3** is working for you (seems pretty straightforward when you know the values ahead of time), and looks like based on your edit you were able to get it to work with Bson conversions for dynamic data.

Only thing I would suggest is that you may be able to perform the conversion a bit more easily. You can see from [the docs here](https://docs.rs/bson/0.13.0/bson/enum.Bson.html#implementations) that Bson impls `From` for various flavors of string. That being the case, you may be able to save an allocation compared to your edit above using this:

```rust
let cats: Vec<Bson> = some_str.split(",").map(From::from).collect();
let cursor = collection.find(Some(doc! {"categories": {"$in": cats}}), None);
```

**Disclaimer:** I haven't run the above code, but it should compile and give you what you are looking for. It also saves you from having to allocate two vecs.

**Comment by thedodd** [comment]
Let me know if that helps. If so, mind closing this issue?

**Comment by deltavin** [comment]
Hi @thedodd 
Feel free to close this. The bson trait trick will come handy. 

Thanks for creating the driver.

**Comment by thedodd** [comment]
So, I’m not actually a maintainer (yet), so I can’t close.

**Comment by jcdyer** [comment]
@deltavin I've recently updated the `bson` crate to accept a broader range of From<> implementations in https://github.com/zonyitoo/bson-rs/pull/130.  I don't think that PR was done in time to be included in bson v.0.14, though.  You can try it out by declaring the latest commit as an override in your Cargo.toml:

```
[patch.crates-io]
bson = { git = "https://github.com/zonyitoo/bson-rs", commit = "3654859" }
```

Please see if that meets your needs.

**Comment by jcdyer** [comment]
@saghm @kyeah This issue can be closed.
