### ISSUE TITLE
Create changelog and prep 0.4 release.

### ISSUE THREAD

**Issue by thedodd** [mongodb-labs/mongo-rust-driver-prototype#306]
Add this here per our discussion in #299. It has been on my shortlist, but I don't want to forget.

**Comment by nylar** [comment]
@thedodd Any movement on a 0.4 release? It would be nice to have #305 in a released version

**Comment by thedodd** [comment]
Hey @nylar, my plan is to let @saghm or @kyeah handle that actually. I don't have permissions to actually do any releasing on this crate or anything. Hopefully it gets some movement soon though.

**Comment by saghm** [comment]
Sorry about the delay! I'll work on getting this done

**Comment by saghm** [comment]
Just pushed out v0.4.0! FYI, this will likely be the last minor version bump of this driver that we do; my team at MongoDB and I have been hard at work for a few months now on an alpha release of an officially supported Rust driver, so we plan on focusing our efforts there moving forward
