### ISSUE TITLE
Authentication succeeds while it shouldn't

### ISSUE THREAD

**Issue by nkostoulas** [mongodb-labs/mongo-rust-driver-prototype#307]
I'm using something like this:
```
let uri = "mongodb://user:pass@localhost:27017/coordinator";
let client = Client::with_uri(uri)?;
```

No error is reported, while when I run the same on command line it fails with "login failed". That's because this database has no authentication.

Is this normal or should I use some different method to capture the connect error?

**Comment by jjgumucio** [comment]
If the database does not need authentication then omit the `user:pass@` part of the connection url and try.

Hope it helps

**Comment by nkostoulas** [comment]
That's a hack not a solution.

**Comment by saghm** [comment]
The driver currently doesn't support specifying authentication credentials in the URI. The only way to authenticate that's currently implemented is using `Database::auth` after creating the client.

**Comment by nkostoulas** [comment]
Ah cool!

**Comment by nkostoulas** [comment]
I guess this means if it were to lose connectivity then I would need to do authentication again?

Also for reconnect interval and tries, are the default values used? I've noticed reconnect works but could not find any config for it.

**Comment by saghm** [comment]
Yes; authentication is done on a per-connection basis, so if you had to close and reopen a connection, you'd need to auth again. For context, modern MongoDB drivers now deprecate lazy authentication for reasons like this and prefer eager authentication, but this hasn't been implemented yet for this driver.

Can you clarify what you mean by "reconnect interval and tries"? The driver mechanism that the driver uses to keep track of the topology is a bit complex, so it's not quite as simple as "wait N milliseconds and reconnect" when a network error occurs. Is there a specific MongoDB drivers option that you're wondering about (e.g. `serverSelectionTimeoutMS`)?

**Comment by nkostoulas** [comment]
I was talking more about the case where there is a connectivity error and when the client reconnects it needs to do auth again. Being unaware whether that happened means that before each db call this auth will need to be applied. I guess this is resolved with different auth types.

I meant reconnectInterval and reconnectTries which I’ve seen in the node mongo driver. Are these driver specific?

**Comment by saghm** [comment]
At least as far as I'm aware, those are specific to the Node driver. From a quick grep, they aren't mentioned at all in the [specifications](https://github.com/mongodb/specifications), and I wasn't previously aware of them. I'll check with some of the people who work on that driver to learn more about what they do so I figure out what the equivalent Rust behavior is.

**Comment by nkostoulas** [comment]
Ah right. Thanks!

**Comment by nkostoulas** [comment]
Sorry for the question which might not be exactly fit for this issue but I was wondering if you could share some feedback.

I've been sharing the same db connection between two threads, which is fine since it's thread safe. I'm using basic auth though and the only way to make sure this retains is to do db.auth() before each call to the database. It appears though that if both threads try to do this auth at the same time auth fails. Are you aware of any way to check that we are authenticated without having to do auth() every time? Or would it be better to use a different connection per thread?

**Comment by saghm** [comment]
Hello again! With regards to `reconnectInterval` and `reconnectTries`, the Node driver team informed me that those are legacy options from before the Node driver was updated to more fully comply with the specs, so they aren't anything that other drivers will implement.

Unfortunately there isn't any existing API in the driver that lets you determine if you're already authenticated or not. As a workaround, you can run the [`connectionStatus` command](https://docs.mongodb.com/manual/reference/command/connectionStatus/) and inspect the response to check if your connection is already authenticated or not.

**Comment by nkostoulas** [comment]
ok thanks. that's what I've ended up doing and also wrapping the Database instance with a Mutex as authenticated calls seem not thread safe.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
