### ISSUE TITLE
Large writes fail with broken pipe error

### ISSUE THREAD

**Issue by Paul-E** [mongodb-labs/mongo-rust-driver-prototype#311]
Writing large data structures to the database will cause the write to fail with a `IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })` error. The server will see something along the lines in the log:

    2019-04-14T17:12:16.317-0400 I NETWORK  [conn11] recv(): message msgLen 156903002 is invalid. Min 16 Max: 48000000
    2019-04-14T17:12:16.317-0400 I NETWORK  [conn11] Error receiving request from client: ProtocolError: recv(): message msgLen 156903002 is invalid. Min 16 Max: 48000000. Ending connection from 127.0.0.1:43012 (connection id: 11)

The follow is a simple example program that will generate the broken pipe error:

    #[macro_use(bson, doc)]
    extern crate mongodb;
    
    use mongodb::{Bson, Client, ThreadedClient};
    use mongodb::db::ThreadedDatabase;
    
    fn main() {
        println!("Generating data");
        let big_data: Vec<_> = (0..12001000).map(|x| Bson::from(x)).collect();
        let to_insert = doc!{"test": big_data};
        println!("Connecting to database");
        let client = Client::connect("localhost", 27017).unwrap();
        let collection = client.db("test").collection("test");
        println!("Attempting insert");
        collection.insert_one(to_insert, None).unwrap();
    }

It looks like the Java driver had a [similar issue](https://jira.mongodb.org/browse/JAVA-2716) at some point.

Perhaps more importantly, this error also occurs when you attempt to use insert_many to insert a large number of documents that are each individually below the file size limit.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
