### ISSUE TITLE
problem on DateTime<Utc> type

### ISSUE THREAD

**Issue by phantomxe** [mongodb-labs/mongo-rust-driver-prototype#317]
hi, i'm trying to developing an api with rust + rocket + mongodb. When i insert a document with struct serialized typed datetime, it's saved on db with string type. But when i insert with doc! macro, it's saved on isodate which as it should be. 
```
// On mongodb creatingDate and lastProcessDate is on ISODate type
doc! {
    "id": bson::oid::ObjectId::new().unwrap(),
     "creatingDate": Utc::now(),
     "lastProcessDate": Utc::now(),
     "name": name.to_owned(),
     "color": color.to_owned(),
};

// On mongodb creatingDate and lastProcessDate is on string type
#[derive(Serialize, Deserialize, Debug)]
pub struct MyStructType {
#[serde(rename = "_id")]
    pub id: bson::oid::ObjectId,
    pub creatingDate: DateTime<Utc>,
    pub lastProcessDate: DateTime<Utc>,
    pub name: String,
    pub color: String,
}

let a = MyStructType {
     id: bson::oid::ObjectId::new().unwrap(),
     creatingDate: Utc::now(),
     lastProcessDate: Utc::now(),
     name: name.to_owned(),
     color: color.to_owned(),
};
```

But when i get a document from db and deserialize it, i got "a formatted date and time string or a unix timestamp" error. How can i solve it?

**Comment by saghm** [comment]
Hi! The `doc` macro and all of the serialization/deserialization logic are actually implemented in the [`bson` crate](https://github.com/zonyitoo/bson-rs/). Could you file a ticket there? Apologies for the inconvenience; the owner of the `bson` crate isn't actually a contributor to this project, and I'm not actually an official contributor to the `bson` crate, so I want to make sure that the correct people get their eyes on this issue and that any other users who have the same issue now or in the future can easily find the issue.
