### ISSUE TITLE
Performance is still bad #2

### ISSUE THREAD

**Issue by inv2004** [mongodb-labs/mongo-rust-driver-prototype#333]
Please find initial problem and code here https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/277

I just decided to check the crate performance one more time: situation is much better than here https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/277, **but still significantly slower than in mongo_driver**.

mongo_driver: avg run: 217ms
code: https://gist.github.com/inv2004/c1470f407c3b76a5a2d6237e67a023e1

mongodb: avg run: 678ms
code: https://gist.github.com/inv2004/87b49ee4217872d9260e13a09e6bf524

**Comment by saghm** [comment]
Hi @inv2004! It's been noted a couple places in other issues/PRs (although not officially announced yet), but my team at MongoDB and I have been working on a new Rust driver that will officially supported! We expect to have an alpha out sometime in the not-too-distant future, so there will not likely be any more releases for this specific project (i.e. the prototype). Once we have an alpha available, I'll make sure to link to the announcement in this thread (and all other open ones on this repository), and we'll definitely be looking for feedback both in terms of the API ergonomics and performance, so I hope you'll check it out once that happens!

**Comment by inv2004** [comment]
@saghm 
It would be interesting to know mode details about your plans:
Are you going to make rust-only version of the driver or you want to make c-bindings?

Regards,
  Alexander.

**Comment by saghm** [comment]
The new driver will still be pure Rust; it won't wrap the C driver

**Comment by brunobell** [comment]
So happy to know that this pure rust mongodb driver will have new releases.
Please let us know when it's out, thanks. @saghm

**Comment by jcdyer** [comment]
@inv2004 and others: If you need better performance now, you can check out #326.  I've also got a branch of bson-rs where I'm implementing a zero-copy RawBson format that would eliminate the need to pre-parse the bson into a tree structure before extracting data or deserializing to other formats, but 1. The branch doesn't implement deserialization for all field types yet (hopefully by end of year), and 2. I haven't begun to integrate it into this driver yet.

**Comment by jcdyer** [comment]
@saghm If you're looking for contributors to help with the new driver, I'd love to help out.

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
