### ISSUE TITLE
AWS DocumentDB compatibility 

### ISSUE THREAD

**Issue by anthonyjchriste** [mongodb-labs/mongo-rust-driver-prototype#334]
Hello, 

We've recently migrated from a self hosted MongoDB server to AWS DocumentDB (which is MongoDB 3.6 compatible). I can connect to the cluster on AWS DocumentDB, but every time I try to perform any query, I get the following error:

> Err(OperationError("Legacy opcodes are not supported"))

Do you know of any workarounds? If not, where would I begin to look to implement a PR?

Thank you for your time.

**Comment by saghm** [comment]
Hello! I don't know of any workarounds for getting DocumentDB to support legacy opcodes. For context, MongoDB 3.6 added a new wire protocol opcode called OP_MSG type for communication between the drivers and the server, but newer versions of the server still support legacy opcodes; I suspect that DocumentDB only supports OP_MSG, while this driver only supports the former.

**Comment by anthonyjchriste** [comment]
Thank you for the response! I suspected it was something along those lines. I was able to find more information about the OP_MSG protocol here: https://github.com/mongodb/specifications/blob/master/source/message/OP_MSG.rst

It looks like quite the undertaking, but I have a vested interest in accessing DocumentDB from AWS. Is this project open to PRs if I were to look into implementing the OP_MSG protocol?

**Comment by saghm** [comment]
We actually aren't planning on doing any more releases of this driver; my team and I at MongoDB have been working on writing an official Rust driver for MongoDB, and we're planning on releasing an alpha in the near future. Similar to the other official MongoDB drivers, we don't do any testing against DocumentDB, and DocumentDB is not officially supported by our drivers, but the new driver will have OP_MSG, and you're welcome to try it out once it's released.

**Comment by anthonyjchriste** [comment]
That's great news! I look forward to testing the alpha-release of the official mongo driver for rust.
