### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by saghm** [mongodb-labs/mongo-rust-driver-prototype#88]
The first attempt at multithreading support was made in #87, but the solution of aliasing `Arc` types and then adding traits is rather messy. There should be a cleaner solution implemented at some point to avoid forcing users to import both the alias types _and_ the bulky traits.

**Comment by kyeah** [comment]
My two cents (as mentioned): A self-referential `Arc` gets rid of both the alias/inner class and trait bloat while minimizing the changes made to the existing structs and making no changes to the user-facing API (8080b80).

```rust
pub fn new(...) -> Arc<Client> {
    let mut client = Client { 
        arc: None,
        ...
    };

    let arc = Arc::new(client);
    client.arc = Some(arc.clone());
    arc
}
```

- No additional traits to import or additional structs.
- Documentation shows up correctly (functions + documentation not hidden within traits, don't have to separate function docs in code)
- Easier to maintain and expand classes without duplicating functions in trait and impl

**Comment by saghm** [comment]
I think I'd disagree with the last bullet point; having a reference to the same type is obviously useful, but having a pointer to the exact same struct itself seems messy and unneccessary;  the same functionality could be achieved by encapsulating all of the state in one struct, then having an outer struct with only an `Arc` field containing the state. Then one could implement the API on the outer struct and *only* make the outer struct visible. 

Not sure how clear that was, but I'm envisioning something like this:

```
struct ClientInner {
    // Client fields
}

pub struct Client {
    inner: Arc<ClientInner>,
}

impl Client {
    // API methods (and helpers) go here
}
```

...and similarly for `Database`. Obviously there would need to be methods exposing some/all of the fields of `ClientInner` through `Client` since `Database` would need access to them through its `client` field, but this seems rather inconsequential. This design would give all of the same benefits of the self-referential struct (maintaining the API, ease of adding new methods, correct documentation), but without the messiness of self-reference.

**Comment by kyeah** [comment]
Like you ran into when trying to implement this previously, there's no way to implement client methods in ClientInner without having a self-reference to itself, and there's no way to implement methods in Client without reducing the functionality of anything that only receives a reference to ClientInner (which database would have to take). I would actually argue that obfuscating the client architecture with a split class that accomplishes both goals in a complex way is messier than adding a private self-reference field and cloning it when you need to, which is safe, takes about three lines, and keeps both the API and documentation intuitive and user-friendly.

**Comment by saghm** [comment]
I'm not sure what you mean by "anything that only receives a reference to ClientInner"; in  the design I proposed, it isn't even public. I guess I didn't explicitly say that everything would have a reference to `Client` rather than `ClientInner`, but I thought that the fact that `Client` was public and `ClientInner` wasn't would be enough. Similarly, I'm confused by your saying "there's no way to implement client methods in ClientInner"; the whole design I explained was that `ClientInner` **wouldn't** have any methods, hence the code sample I wrote only having an implementation block for `Client` and `ClientInner` being private.

**Comment by kyeah** [comment]
Yes, I'm describing two possibilities: methods in Client, or in ClientInner. You can't pass Arc references of `Client` because the `Client` class is unaware of whether it is being wrapped by an Arc or not, which is the reason you have an `Arc<ClientInner>` in the first place -- to clone that and pass it to `Database::new`.

**Comment by saghm** [comment]
Ah, I see.

**Comment by saghm** [comment]
Have you actually gotten the code sample you wrote above to compile? It seems kind of fishy that both the Arc and the Client could own each other and then have only one returned.

**Comment by kyeah** [comment]
^ true. The code sample compiles, but it turns out `client.arc = Some(arc.clone());` doesn't modify the moved `client` value (although it still builds??), so the hunt for a solution continues.

**Comment by saghm** [comment]
Runtime issue? \*gasp\*

**Comment by naicode** [comment]
No more like a  bug in the borrow checker. The Error Message should have been:
 ```partial reinitialization of uninitialized structure `Client` [E0383]```

Client is moved int Arc so the client he modifies is just some "dead" stack space where once the client now moved into Arc::new had been lain. You cannot read from this "dead" stack (prevented by borrow checker) and when the stack is dropped no Drop impl for whatever you have assigned there will be run (preventing Arc's counter from ever reaching 0 in this case).

Also Arc just allows immutable borrows (because it only has atomizity for it's counter but not it's values) so you have to use RefCell to do  "just one mutable access" checks at runtime. But then RefCell is not Sync/Send so Arc won't be either. (so no sending a clone to another thread).  Therefor you have to use a `Mutex` insted of RefCell leading to:

`Arc<Mutex<Client>>`

so the function would be:
```rust
pub fn new(...) -> Arc<Client> {
    let client_arc = Arc::new(Mutex::new(Client { arc: None ... }));
    //client_arc ->implizit deref to Mutex -> lock -> (can fail if poisoned) so is Result -> unwrap()
   //-> get som mutex guard -> implicit borrow_mut -> now have a   &mut client
    let mut client = client_arc.lock().unwrap();
    //the mutabel borrow is capsuled into the mutex so the arc is only borrowed read only
    //and clone() can be called
    client.arc = client_arc.clone();
    client_arc
}//lock will be implicitly released when the guard is dropped
```

Disclaimer I did not test this code 

Also note that as long as you don't add some drop magic a self referencing circular reference will always think that some reference is left (itself) and therefore never drop -> Memory is leaked

**Comment by saghm** [comment]
Can you give an example of code that would cause the error message you mentioned? It would help me to understand the issue at hand.

Also, I'm not sure I fully understand the rationale for wrapping the client in a mutex; instead of borrowing the client, shouldn't the user just be cloning the Arc to make another reference to it? It's my understanding that reference counting is supposed to be used as an alternative to using the regular borrowing semantics.

**Comment by naicode** [comment]
[TL;TR Rc/Arc -> multiple **read only** references]

Yes Referenc Counting is a alternative. 
But with "just" Reference Counting it is limited in this way:
- if there is more then one Rc "referenc"* all borrows are immutable
- if there is only one Rc you can also borrow mutable (but this api part is still unstable)
(else it would conflict with the borrow checker rules)

So if you want to have shared mutable state you have to add some logic witch implements at run-time guarantees that there can only be one mutable access at a time (and no immutable ones if there is one),
even with multiple Arcs and tried parallel access.

This is done by types witch have interior mutability, aka witch can be mutated even
if they are referenced read-only (Thy use some unsafe sharing methods internally and
add run-time safety checks to expose a safe API). 

The default safe type for interior mutability is `RefCell`, witch exposes
a `borrow` and `borrow_mut` method but `RefCell` is not thread safe. A thread safe
struckt with interior  mutability is `RwLock` (or `Mutex`).

`RwLock` is a thread safe equivalent of `RefCell` and allows
multiple read-only references at a time or one write reference, 
where `Mutex` only allows one write reference but can e.g. be 
used with types witch are `Send` but not `Sync`.

Note that `Arc`/`Mutex`/`RwLock` have the quirks that you
can construct them with non threadsafe data (e.g. not Send)
but then the compiler will determine that they are themself not
threadsafe and prevent any Cross Thread usage of them.
This is for some generic corner cases but it can be a bit confusing
if the compiler tells you that e.g. Arc can't be send to another thread.

**Comment by kyeah** [comment]
Hey @naicode, we are avoiding the use of mutable wrappers over the Client itself, as that will open up the possibility of poisoning the lock and killing the entire client if one thread panics. Although the Client itself (Arc<ClientInner>) has exterior mutability, we are using interior mutability wrappers at a finer level for updating the topology and server listeners. 

The current client shares mutable state -- it is just implemented at a lower level to protect against poisoned locks and to improve concurrency by allowing multiple threads to access the client at once. Note that in the code sample above, the return value is an `Arc<Mutex<Client>>` instead of `Arc<Client>`, so client usage would still require a thread to lock the client before using it.

**Comment by inv2004** [comment]
Are there any examples how to use ThreadedClient or ThreadedDatabase?

Thank you,

**Comment by saghm** [comment]
Hi @inv2004! You don't actually need to do anything beyond importing them; they're simply traits defined so that we can define methods on `Arc<ClientInner>`. We defined it this way because it isn't possible to define methods on this type alias directly.

@kyeah on an unrelated note, I did actually come up with a way a little while back to solve this issue without needing a trait! (I didn't come up with it back when we originally wrote this because I didn't fully understand how traits/derive worked back then). Here's what I think is the "correct" way to do this:

```
use std::sync::Arc;

// By deriving `Clone`, we use `Arc`'s implementation of `Clone::clone` whenever we clone the Client. `Client` itself will contain no other fields, so we don't have to worry about thread-safety beyond this.
#[derive(Clone)]
pub struct Client {
    inner: Arc<ClientInner>,
}

struct ClientInner {
    // topology
    // read preference
    // read concern
    // write concern
    // etc.
}

impl Client {
    // All of the methods go here (and none go on `ClientInner`); we just use `self.inner.foo` instead of `self.foo` everywhere in the mod definitions. This also allows us to have private methods on `Client`, which we couldn't do with a trait.
}

#[derive(Clone)]
pub struct Database {
    inner: Arc<DatabaseInner>,
}

struct DatabaseInner {
    client: Client,
    // name
    // read preference
    // read concern
    // write concern
    // etc.
}

impl Database {
    // Similar to `Client`, everything goes here
}

pub struct Collection {
    client: Client,
    db: Database,
    // name
    // read concern
    // write concern
    // etc.
}

impl Collection {
    // Similar to before, we have no need for a CollectionInner
}
```

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Comment by saghm** [comment]
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
